### ISSUE TITLE
Raspberry PI5 not working

### ISSUE THREAD

**Issue by nonuser666** [Leo-C/kodi.addon.autoexec#2]
PI5 not working.

Feel free to reach out to test the setup.

**Comment by Leo-C** [comment]
I've successfully tested latest version with RPi5 / LibreElec 11.0.6.

Because minor enhancement are made (I suspect that even without these, plugin worked), please be more specific about behavior (and other details)

**Comment by nonuser666** [comment]
I am missing something and i have no idea what it is.

Could you make a short video about the installation, or a detailed guide
with pictures?

My goal is to have the Pi as a digital signage, with auto ON - OFF timer
function.

Do you think is it possible?

**Comment by Leo-C** [comment]
Hi,
You have to install from a .zip, and then configure to start another addon at kodi startup
(simply selecting from a listbox in configuration page).

e.g. if you want to start a video when Pi starts, then you have to install also an other addon of mine
https://github.com/Leo-C/script.video.autoplay
and select video from configuration of last addon

(I close issue; please re-open if you find some bug)

**Comment by Leo-C** [comment]
the issue was opened due to usage trouble, not for a bug

**Comment by nonuser666** [comment]
Okay thank you!

If i stuck is there a way to contact with you privately?

**Comment by Leo-C** [comment]
Please, write here if you need support: this can be useful to me to refine documentation if something is missing or unclear

**Comment by nonuser666** [comment]
Sure. Soon i make a video where i am at. And send it to you.

**Comment by nonuser666** [comment]
[image: image.png]

I got it! It is working! Thank you so much!

Do you have any tips on how can the Pi auto turn ON and OFF in a
specific time frame?
For example: every day, ON: 9:30AM ---> OFF: 20:30

In Raspbian crontab worked well, do you think it could be a solution?

I found this:
https://github.com/robweber/cronxbmc

Looks promising.

When this is all done I will make a tutorial for noobies like myself.




Leonardo ***@***.***> ezt írta (időpont: 2024. febr. 4., V,
15:32):

**Comment by Leo-C** [comment]
mmh, if I understand right your use-case, you can:

- start RasPi with a video in loop using my 2 plugins (https://github.com/Leo-C/service.autoexec.addon + https://github.com/Leo-C/script.video.autoplay)
- shutdown at desired time RasPi using https://github.com/robweber/cronxbmc (I have no precise idea as configuration GUI is; maybe I'll try to install next week)
- after a while after shutdown, switch-off RasPi with a mechanical / electronic timer attached to power
- power timer can restart RasPi next day, and cycle restart ...

PS I cannot see you photo if you attach by email: please attach it using web GUI at https://github.com/Leo-C/service.autoexec.addon/issues/2

**Comment by nonuser666** [comment]
I have tested https://github.com/robweber/cronxbmc.

It is not working.

I will try manually modify the crontab.

You understand my plan right.

Except i would like not to use an external timer switch.

Just to put the Pi at a low state mode, and than reboot at the morning.

# 0 9 * * * root echo 'on 0.0.0.0' | cec-client -s -d 1
#30 20 * * * root echo 'standby 0.0.0.0' | cec-client -s -d 1
# reboot at 10:00 AM
#57 9 * * * root /sbin/shutdown -r now

Something like that.

**Comment by Leo-C** [comment]
Hi, a part [cronxbmc](https://github.com/robweber/cronxbmc), I understand your plan.

Only I suggest to schedule standby (also with `cec-ctl` if `cec-client` is not available) and restart Kodi (without 'on' command, only using Video Autoplay to start video after boot), because after TV switch off often RasPi lose control of CEC bus.

Note also that - after TV switch-off - video continue to play in loop (unless you schedule stop with a [built-in](https://kodi.wiki/view/List_of_built-in_functions#Player_built-in's) command)

**Comment by nonuser666** [comment]
Hi!

Sorry for the late reply.

I am struggling with the crontab promts, i couldn't not figure out your recommendations. 

Could you write me a promt for the following that works?

"Only I suggest to schedule standby (also with cec-ctl if cec-client is not available) and restart Kodi (without 'on' command, only using Video Autoplay to start video after boot), because after TV switch off often RasPi lose control of CEC bus."

"Note also that - after TV switch-off - video continue to play in loop (unless you schedule stop with a built-in command)"

**Comment by nonuser666** [comment]
My solution will be more simple.

In crontab at fix time i will use the shutdown command and plug the RPI into a timer plug, that will boot up the system.

Not elegant but works and easy.

**Comment by Leo-C** [comment]
Hi,
sorry for long response time, but I'm quite busy, and I'm concentrating on adaption for RPi5 of another [my project](https://github.com/Leo-C/script.media.motiondetect).

Your last solution is my first suggestion for you;
otherwise you can work on your original idea, but I suggested in my previous post some points of attention:
- you can use `cec-ctl` instead `cec-client` if you have trouble
- sometimes TV cannot be turned on by CEC command after switch-off, so I suggest to restart Kodi to power-up TV and restart video using my plugins (and Kodi will restore CEC link with TV)
- a caveat for my autoplay plugin: if you switch-off TV via CEC with a command, video continue to play, then you have to stop it with command `kodi-send --action="PlayerControl(Stop)"`

**Comment by Leo-C** [comment]
Finally I do my homework!

It seems that [many CEC commands do not work into Kodi](https://forum.libreelec.tv/thread/22882-cec-client-does-not-work-on-nightly-9-8-rpi-4b/);
instead you can uso some Kodi built-in commands (but you cannot switch-off TV):
- `ActivateScreensaver` (that starts Screen Saver, by default reducing brightness)
- `CECActivateSource` (that stop Screen Saver)
- `ShutDown` (to shutdown Kodi; you can switch-off and restart Raspberry + TV with a power timer)

Moreover I've tested [cronxbmc ](https://github.com/robweber/cronxbmc) (that works also with RPi5 / LE21.alpha: I've tested it) to start above commands using: _Add Job_ -> _Built-in Function_

**Comment by nonuser666** [comment]
Hi. 

New issue occurred.

The RPi5 is rebooting fine, but randomly its stuck at the main menu and asking where to continue the video. 

![20240419_111755.jpg](https://github.com/Leo-C/kodi.addon.autoexec/assets/80016058/6586bfa2-6065-4f83-b5fc-6b4129b1eabc)

I think it's the player's issue. I can find any options to ignore that after the reboot its automatically starts at the beginning of the video loop, and doesn't show up the question where i want to start the video. 

Do you have any options to try out?

**Comment by Leo-C** [comment]
Hi,
my addon play video in loop after reboot, but ever from start.

Are you sure that after reboot none of input controls interact with Kodi? (e.g. a pause on a remote control or a mouse click can show screen sent by you)

**Comment by nonuser666** [comment]
Hi.

No input controller is connected to the RPi.

The TV automatically detect the HDMI signal and it's turning On when the RPi starts trigger by the power timer. 

![20240419_154724.jpg](https://github.com/Leo-C/kodi.addon.autoexec/assets/80016058/2158127f-e547-417f-b2d3-0b9a1c541f9c)

Can it be that the TV send a signal to the RPi?

But the strange thing is that it's randomly happening, around 50% of the time it's starts the loop the other 50% its stuck at the screen i sent before.

Should I make a clean install?

**Comment by Leo-C** [comment]
Yes, you can try with a fresh install.
But, if you shut down RPi only with power timer, I believe that RPi "remember" playing state of video: you can try some times with _graceful_ shutdown in a manual way first stopping the video (e.g. using a mouse attached to RPi)

PS TV can send signals to RPi via HDMI-CEC, but I don't believe is you case

**Comment by nonuser666** [comment]
I investigated further.

And after around 60 reboots i noticed a parent.

I have 1 video file in loop.
It's 8:20 seconds.

If I reboot within ~ 3 minutes it's working properly.

But if I exceed the ~3 minutes mark it will boot to the [resume from] or [play from beginning] options.

If i choose [resume from] and reboot the same option come up after reboot.

If I choose [play from beginning] it clears the mistake and works fine until it's exceeding the 3 minutes mark.

How many and how long your video files are?

I can send you a video, it's the beginning of the testing.

**Comment by nonuser666** [comment]
Unfortunately turning it manually its not an option, it's works as a digital signage in a studio.

I use crontab:

30 21 * * */sbin/shutdown -r now

Any other suggestions?

**Comment by Leo-C** [comment]
Yes, I understand, but manual testing is useful to find a correct shutdown procedure.
I think you have also to schedule stop of movie player (before shutdown!) with my suggestion of 17-feb

**Comment by nonuser666** [comment]
Can you recommend a CLI promt to stop the video player?

Should it be crontab also?

I searched in Google but couldn't find any useful. :(

I will test it manually as well in the next days, and let you know.

**Comment by Leo-C** [comment]
try following command in crontrab before shutdown:
`kodi-send --action="PlayerControl(Stop)"`

**Comment by nonuser666** [comment]
<img width="441" alt="Screenshot 2024-05-23 203712" src="https://github.com/Leo-C/kodi.addon.autoexec/assets/80016058/51d2d897-8f47-4a36-82f8-1292015539ed">
<img width="267" alt="Screenshot 2024-05-23 203745" src="https://github.com/Leo-C/kodi.addon.autoexec/assets/80016058/4e43ead0-a088-4f0e-8434-d15d17ecef07">

I tested the command. Unfortunately it is not solving the problem. 
Now I reinstall the plugins and test it again.

**Comment by nonuser666** [comment]
The same problem still appear after the Plugin reinstall. 
Also if i do it manually.

Now I try with short videos less than 2 minutes. 

If that doesn't work than reinstall.

**Comment by nonuser666** [comment]
Testing with short clips working so far. 

Can you have a test with a 8min or longer video if you get the resume from --:-- /play now window? 
Wait a few minutes or forward in a few times on the timeline close to the end. 

If all working well tomorrow I make a tutorial for noobs like me :)

**Comment by nonuser666** [comment]
![image](https://github.com/Leo-C/kodi.addon.autoexec/assets/80016058/0038513f-0c13-498b-9edf-7f004e549047)
With a fresh install i got the same problem

**Comment by nonuser666** [comment]
![image](https://github.com/Leo-C/kodi.addon.autoexec/assets/80016058/a9ef708c-bc99-4451-87ab-cf649160cef1)
same issue on 12.0.0

**Comment by nonuser666** [comment]
![image](https://github.com/Leo-C/kodi.addon.autoexec/assets/80016058/128d8ced-be8e-4ba2-8cad-55d90112cb1e)

**Comment by nonuser666** [comment]
If the plugins are disabled an the settings changed as follows "Default select action: Resume "  and "Default play action:
Resume" than the prompt disappears. 

When the plugin reactivated the "Resume from 00:06:03/Play from beginning" prompt re reappear. 

Any suggestion to edit the setting at the plugin?

**Comment by nonuser666** [comment]
Bug found!

Please change the code in the autoplay.py the following:
![image](https://github.com/Leo-C/kodi.addon.autoexec/assets/80016058/d7f3b261-0b0c-4619-ad4f-6052ff8e2286)

xbmc.executebuiltin('PlayMedia("%s",resume)' % playlist_file)

**Comment by Leo-C** [comment]
Hi,
your suggestion can fix behaviour (meaning that not show choose between resume or restart), but I suggest to use "noresume" (as stated in https://kodi.wiki/view/List_of_built-in_functions - Player built-in's) to restart from beginning after reboot.

(I was not aware that default value - without "resume" or "noresume" - is to show the choice)

**Comment by nonuser666** [comment]
Hi!

I made a tutorial all the steps are included for beginners. 
https://youtu.be/tikUbvffnlY
